data:extend({
	{
		name = 'aotd_nauvis',
		type = 'string-setting',
		setting_type = 'startup',
		default_value = 'bright',
		allowed_values = { 'default', 'bright', 'nauvis', 'always_day' },
		order = '1',
	},
  {
		name = 'aotd_vulcanus',
		type = 'string-setting',
		setting_type = 'startup',
		default_value = 'bright',
		allowed_values = { 'default', 'bright', 'nauvis', 'always_day' },
		order = '2',
	},
  {
		name = 'aotd_fulgora',
		type = 'string-setting',
		setting_type = 'startup',
		default_value = 'bright',
		allowed_values = { 'default', 'bright', 'nauvis', 'always_day' },
		order = '3',
	},
  {
		name = 'aotd_gleba',
		type = 'string-setting',
		setting_type = 'startup',
		default_value = 'bright',
		allowed_values = { 'default', 'bright', 'nauvis', 'always_day' },
		order = '4',
	},
	{
		name = 'aotd_aquilo',
		type = 'string-setting',
		setting_type = 'startup',
		default_value = 'bright',
		allowed_values = { 'default', 'bright', 'nauvis', 'always_day' },
		order = '5',
	},
})